INSERT INTO notifications (receiver_id, sender_id, title, content, notification_type, read, created_at)
VALUES
(16, 1, 'Reservation Request', 'Request for booking Seaside Villa', 'RESERVATION_REQUEST', true, '2025-06-27'),
(16, 2, 'Reservation Request', 'Request for booking Seaside Villa', 'RESERVATION_REQUEST', true, '2025-06-27'),
(16, 3, 'Reservation Request', 'Request for booking Seaside Villa', 'RESERVATION_REQUEST', false, '2025-06-28'),
(16, 4, 'Reservation Request', 'Request for booking Mountain Retreata', 'RESERVATION_REQUEST', true, '2025-05-25'),
(16, 5, 'Reservation Request', 'Request for booking Mountain Retreat', 'RESERVATION_REQUEST', true, '2025-05-24'),
(17, 6, 'Reservation Request', 'Request for booking City Apartment', 'RESERVATION_REQUEST', true, '2025-05-23'),
(17, 7, 'Reservation Request', 'Request for booking City Apartment', 'RESERVATION_REQUEST', true, '2025-05-22'),
(18, 8, 'Reservation Request', 'Request for booking Countryside Cottage', 'RESERVATION_REQUEST', true, '2025-05-21'),
(18, 9, 'Reservation Request', 'Request for booking Countryside Cottage', 'RESERVATION_REQUEST', true, '2025-05-20'),
(19, 10, 'Reservation Request', 'Request for booking Beach House', 'RESERVATION_REQUEST', true, '2025-05-19'),
(19, 11, 'Reservation Request', 'Request for booking Beach House', 'RESERVATION_REQUEST', true, '2025-05-18'),

(1, 16, 'Host Response', 'Request accepted for booking Seaside Villa', 'HOST_RESPONSE', false, '2025-06-28'),
(2, 16, 'Host Response', 'Request accepted for booking Seaside Villa', 'HOST_RESPONSE', false, '2025-06-27'),
(4, 16, 'Host Response', 'Request accepted for booking Mountain Retreata', 'HOST_RESPONSE', true, '2025-05-25'),
(5, 16, 'Host Response', 'Request accepted for booking Mountain Retreat', 'HOST_RESPONSE', true, '2025-05-24'),
(6, 17, 'Host Response', 'Request accepted for booking City Apartment', 'HOST_RESPONSE', false, '2025-05-23'),
(7, 17, 'Host Response', 'Request accepted for booking City Apartment', 'HOST_RESPONSE', false, '2025-05-22'),
(9, 18, 'Host Response', 'Request accepted for booking Countryside Cottage', 'HOST_RESPONSE', false, '2025-05-21'),
(9, 18, 'Host Response', 'Request accepted for booking Countryside Cottage', 'HOST_RESPONSE', true, '2025-05-20'),
(10, 19, 'Host Response', 'Request accepted for booking Beach House', 'HOST_RESPONSE', false, '2025-05-19'),
(11, 19, 'Host Response', 'Request accepted for booking Beach House', 'HOST_RESPONSE', false, '2025-05-18'),

(16, 1, 'Accommodation review', 'Your accommodation got review (5)', 'ACCOMMODATION_REVIEW', false, '2025-06-28'),
(16, 2, 'Accommodation review', 'Your accommodation got review (3)', 'ACCOMMODATION_REVIEW', false, '2025-06-27'),
(16, 4, 'Accommodation review', 'Your accommodation got review (1)', 'ACCOMMODATION_REVIEW', true, '2025-05-25'),
(16, 5, 'Accommodation review', 'Your accommodation got review (1)', 'ACCOMMODATION_REVIEW', true, '2025-05-24'),
(17, 6, 'Accommodation review', 'Your accommodation got review (5)', 'ACCOMMODATION_REVIEW', false, '2025-05-23'),
(18, 8, 'Accommodation reviewe', 'Your accommodation got review (2)', 'ACCOMMODATION_REVIEW', false, '2025-05-22'),
(18, 9, 'Accommodation reviewe', 'Your accommodation got review (4)', 'ACCOMMODATION_REVIEW', false, '2025-05-22'),
(19, 10, 'Accommodation review', 'Your accommodation got review (3)', 'ACCOMMODATION_REVIEW', false, '2025-05-21'),
(19, 11, 'Accommodation review', 'Your accommodation got review (4)', 'ACCOMMODATION_REVIEW', true, '2025-05-20'),

(16, 1, 'Host review', 'You got review (5)', 'HOST_REVIEW', false, '2025-06-28'),
(16, 2, 'Host review', 'You a got review (4)', 'HOST_REVIEW', false, '2025-06-27'),
(16, 3, 'Host review', 'You got a review (4)', 'HOST_REVIEW', true, '2025-05-25'),
(16, 4, 'Host review', 'You got a review (2)', 'HOST_REVIEW', true, '2025-05-24'),
(16, 5, 'Host review', 'You got a review (4)', 'HOST_REVIEW', false, '2025-05-23'),
(17, 6, 'Host reviewe', 'You got a review (5)', 'HOST_REVIEW', false, '2025-05-22'),
(17, 7, 'Host reviewe', 'You got a review (1)', 'HOST_REVIEW', false, '2025-05-22'),
(18, 8, 'Host review', 'You got a review (3)', 'HOST_REVIEW', false, '2025-05-21');


INSERT INTO notification_preferences (user_id, is_guest, reservation_request_enabled, reservation_cancelation_enabled, host_review_enabled, accommodation_review_enabled, host_response_enabled)
VALUES
(1, true, false, false, false, false, true),
(2, true, false, false, false, false, true),
(3, true, false, false, false, false, true),
(4, true, false, false, false, false, true),
(5, true, false, false, false, false, true),
(6, true, false, false, false, false, true),
(7, true, false, false, false, false, true),
(8, true, false, false, false, false, true),
(9, true, false, false, false, false, true),
(10, true, false, false, false, false, true),
(11, true, false, false, false, false, true),
(12, true, false, false, false, false, true),
(13, true, false, false, false, false, true),
(14, true, false, false, false, false, true),
(15, true, false, false, false, false, true),
(16, false, true, true, false, true, false),
(17, false, true, true, true, true, false),
(18, false, true, false, true, true, false),
(19, false, true, true, true, true, false),
(20, false, true, true, true, true, false),
(21, false, true, true, false, true, false),
(22, false, false, true, true, true, false),
(23, false, true, true, true, false, false),
(24, false, true, true, true, true, false),
(25, false, false, true, true, true, false);